### ISSUE TITLE
Make PyCode_GetFirstFree unstable

### ISSUE THREAD

**Issue by encukou** [capi-workgroup/decisions#18]
As brought up in https://github.com/python/cpython/pull/115781:

`PyCode_GetFirstFree` exposes an implementation detail: in a code object, free variables follow regular ones.

It should be moved to the unstable tier, using the [process in the devguide](https://devguide.python.org/developer-workflow/c-api/#moving-an-api-from-the-public-tier-to-unstable) (which directly follows PEP 689). That is, it's renamed to `PyUnstable_Code_GetFirstFree`, and the old name remains as a deprecated alias until an incompatible change is made. And such a change can't be made before 3.15.

* [x] @encukou: +1
* [x] @gvanrossum
* [x] @iritkatriel 
* [x] @vstinner: +1
* [x] @zooba

Note that Mark Shannon [wants all code API to be unstable](https://github.com/python/cpython/pull/115654#discussion_r1497192136) so there might be follow-ups. But, I don't think any are similar enough to include it in this vote. (Note that `PyCode_GetFreevars` & `PyCode_GetNumFree` expose the the fully public `co_freevars` Python attribute, and its length.)

**Comment by vstinner** [comment]
PyCodeObject API documentation: https://docs.python.org/dev/c-api/code.html

There are already a few unstable functions there:

* PyUnstable_**Code**_New()
* PyUnstable_**Code**_NewWithPosOnlyArgs()
* PyUnstable_**Code**_GetExtra()
* PyUnstable_**Code**_SetExtra()
* PyUnstable_**Eval**_RequestCodeExtraIndex()

**Comment by encukou** [comment]
@iritkatriel, should we wait for your vote?

**Comment by iritkatriel** [comment]
Sorry, I didn't see this for some reason. LGTM

**Comment by encukou** [comment]
Thanks for voting everyone!
