### ISSUE TITLE
Add `PyObject_ClearWeakRefsNoCallbacks`

### ISSUE THREAD

**Issue by colesbury** [capi-workgroup/decisions#25]
### Background

The use case that types with user defined finalizers (i.e., `__del__` methods) need to perform the following sequence if they want to be correct:

* Clear weakrefs and call callbacks (i.e., `PyObject_ClearWeakRefs`)
* Call finalizer (i.e, `PyObject_CallFinalizerFromDealloc`)
* Clear weakrefs *again*, but don't call callbacks (i.e., the proposed `PyObject_ClearWeakRefsNoCallbacks`)

The third-step is performed internally via `_PyWeakref_ClearWeakRefsExceptCallbacks`, but that's not a public API. This is performed internally by [`subtype_dealloc`](https://github.com/python/cpython/blob/ec9d12be9648ee60a2eb02d67069d74f8b314df9/Objects/typeobject.c#L2255-L2257), but extensions cannot always delegate to that function.

Previously, C API extensions used the following pattern, but it's not thread-safe without the GIL and relies on an undocumented private API `_PyWeakref_ClearRef`:

```c
      PyWeakReference **list = PyObject_GET_WEAKREFS_LISTPTR(self);
      while (*list) {
        _PyWeakref_ClearRef(*list);
      }
```

### Proposed API

```c
// Clears the weakrefs for object `obj`, but does not call their callbacks.
PyAPI_FUNC(void) PyObject_ClearWeakRefsNoCallbacks(PyObject *obj);
```

### Implementation

The implementation already exists as the internal-only `_PyWeakref_ClearWeakRefsExceptCallbacks` function. Per @vstinner's suggestion, I'd propose that the `PyObject_ClearWeakRefsNoCallbacks` returns immediately if `obj` does not support weakrefs.

### See also

* [`PyObject_ClearWeakRefs`](https://docs.python.org/3/c-api/weakref.html#c.PyObject_ClearWeakRefs): a similar function, which clears weakrefs **and** calls their callbacks

**EDIT**: Updated name based on @iritkatriel's suggestion

**Comment by gvanrossum** [comment]
No objection from me.

**Comment by iritkatriel** [comment]
I don't think the name `PyObject_ClearWeakRefsExceptCallbacks` is clear. `Except` in particular. 

Something like `PyObject_ClearWeakRefsNoCallbacks` maybe.

**Comment by colesbury** [comment]
I've updated the proposed name

**Comment by vstinner** [comment]
LGTM.

**Comment by gvanrossum** [comment]
WFM.

--Guido (mobile)

**Comment by encukou** [comment]
While the semantics of `PyObject_ClearWeakRefsNoCallbacks` function itself are clear, it seems that anyone calling it is quite deep in implementation details.
I worry that by exposing the function, we're implicitly saying that it's OK to re-implementing `subtype_dealloc`, or at least the “clear/call del/clear again” dance. 

It seems better to expose this as `PyUnstable_Object_ClearWeakRefsNoCallbacks`: if you use this function, you better be checking What's News and you better be prepared to adjust code for each new release.
(Perhaps one of those releases will add a `PyObject_Finalize()` that abstracts away a well-defined chunk of `subtype_dealloc`. But even if we add something like that in 3.14, a transitional `PyUnstable_Object_ClearWeakRefsNoCallbacks` would be nice to have.)

**Comment by colesbury** [comment]
`PyUnstable_Object_ClearWeakRefsNoCallbacks` is fine with me too.

**Comment by colesbury** [comment]
@vstinner - is `PyUnstable_Object_ClearWeakRefsNoCallbacks` okay with you?

**Comment by vstinner** [comment]
> I worry that by exposing the function, we're implicitly saying that it's OK to re-implementing subtype_dealloc, or at least the “clear/call del/clear again” dance.

IMO it's ok to reimplement something like subtype_dealloc, since 3rd party extensions do it, and that's why Sam wants to make the function public. I'm not sure that thr function needs to be tagged as "unstable". The documentation can be clear about where and when it should be used or not.

**Comment by vstinner** [comment]
It seems like we are ok with the feature, but not in which API it should be added: how the function should be named. I'm not sure how to resolve this disagreement, so I propose a poll/vote below.

Function name: please pick only name :-)

`PyUnstable_Object_ClearWeakRefsNoCallbacks()` - unstable API, rationale: https://github.com/capi-workgroup/decisions/issues/25#issuecomment-2107728647

* [ ] @encukou 
* [ ] @erlend-aasland 
* [ ] @gvanrossum 
* [ ] @zooba 
* [ ] @vstinner 

`PyObject_ClearWeakRefsNoCallbacks()` - public API, rationale: https://github.com/capi-workgroup/decisions/issues/25#issuecomment-2125451169

* [ ] @encukou 
* [ ] @erlend-aasland 
* [ ] @gvanrossum 
* [ ] @zooba 
* [ ] @vstinner

**Comment by encukou** [comment]
> IMO it's ok to reimplement something like subtype_dealloc, since 3rd party extensions do it[...] The documentation can be clear about where and when it should be used or not.

I'd need to see that documentation to be convinced.

**Comment by zooba** [comment]
I lean towards the "unstable" marking, just so we can remove it within a release. I wouldn't expect the API to change in any other meaningful way apart from the function no longer doing what the caller thinks it is doing.

**Comment by erlend-aasland** [comment]
I chose `PyObject_ClearWeakRefsNoCallbacks`, but I won't oppose the unstable variant (though I think it is a weak candidate for the unstable tier).

**Comment by encukou** [comment]
We discussed this on a meeting, and decided that it should be unstable API. Please go with  `PyUnstable_Object_ClearWeakRefsNoCallbacks`.
