### ISSUE TITLE
Expose Py_tp_vectorcall in the limited API

### ISSUE THREAD

**Issue by encukou** [capi-workgroup/decisions#41]
`tp_vectorcall` is somewhat tricky to understand, but can bring significant speedups to wrapper code.

In https://github.com/python/cpython/issues/100554, pybind11 and PyO3 maintainers ask to expose it for use with `PyType_FromSpec`/`PyType_GetSlot` and in limited API, and Wenzel sent a [PR](https://github.com/python/cpython/pull/123332) recently.

`tp_vectorcall` needs to match the behavior of a metaclass call, so exposing `tp_vectorcall` limits future changes to `PyType_Type->tp_call`. But, I think that's already something we can't really change.

Does a `Py_tp_vectorcall` slot sound reasonable?

* [x] @encukou 
* [x] @erlend-aasland 
* [x] @mdboom 
* [x] @serhiy-storchaka 
* [x] @vstinner 
* [x] @zooba

**Comment by zooba** [comment]
I disagree with vector call being part of the stable ABI at all, but since that's apparently already been done, then I see no reason to oppose adding a constant that should've been there from the start.

**Comment by encukou** [comment]
@erlend-aasland @mdboom @serhiy-storchaka, what's your opinion?

**Comment by encukou** [comment]
@serhiy-storchaka, do you have any reservations?

**Comment by serhiy-storchaka** [comment]
The vectorcall protocol was added to the Limited API in 3.12. It is too late to change anything here. Not exposing `Py_tp_vectorcall` looks like omission.

**Comment by encukou** [comment]
Thanks for the votes!
