### ISSUE TITLE
Make PyInitConfig_Free(NULL) a no-op

### ISSUE THREAD

**Issue by serhiy-storchaka** [capi-workgroup/decisions#46]
Currently it has an undefined behavior. Few other clearing/destroying functions that take a pointer argument already accept NULL (`PyMem_Free()`, `Py_XDECREF()`, `PyUnicodeWriter_Discard()`). This may slightly simplify the user code (see https://github.com/python/cpython/issues/125234 for example).

* [x] @encukou 
* [x] @erlend-aasland 
* [x] @mdboom 
* [x] @serhiy-storchaka 
* [x] @vstinner
* [x] @zooba

This is completely backward compatible change. I would suggest this also as a general rule, but I do not know other examples of similar C API.

**Comment by mdboom** [comment]
In a debug build, would this `assert` it's non-NULL?

**Comment by mdboom** [comment]
> What do you mean? I suggest to change `PyInitConfig_Free()` so that calling it with NULL will be safe. Currently it crashes on most platforms, so you need to add an extra `if` if there is a chance that the argument is NULL.

Sorry, I was just a bit confused.  In the spirit of being analogous to POSIX `free`, this makes sense, so +1 from me.

**Comment by serhiy-storchaka** [comment]
Yes, to be analogous to POSIX `free`. So we can initialize a variable with NULL and then unconditionally use `PyInitConfig_Free()` in the cleanup code, regardless of whether `PyInitConfig_Create()` was called or the code failed before calling `PyInitConfig_Create()`.

I just realized that this C API is new in version 3.14. Therefore, I believe that this vote was unnecessary.

**Comment by vstinner** [comment]
Ping @encukou and @zooba.

**Comment by zooba** [comment]
LGTM

**Comment by serhiy-storchaka** [comment]
Thank you all for voting and sorry for the noise.
