### ISSUE TITLE
Add `PyWeakref_IsDead()` to test if a weak reference is dead

### ISSUE THREAD

**Issue by colesbury** [capi-workgroup/decisions#48]
**EDIT**: Added, `-1` error return case per @vstinner's suggestion.

**EDIT 2**: @vstinner added a vote.

I propose adding a dedicated C API function to check if a weak reference is *dead*:

```c
// Returns 1 if the pointed to object is dead, 0 if it's alive, and -1 with an error set if `ref` is not a weak reference.
int PyWeakref_IsDead(PyObject *ref);
```

### Motivation

Prior to Python 3.13, you could check if a weak reference is dead via `PyWeakref_GetObject(ref) == Py_None`, but that function is now deprecated. You might try writing an "is dead" check using `PyWeakref_GetRef`. For example:

```c
int is_dead(PyObject *ref) {
    PyObject *tmp;
    if (PyWeakref_GetRef(&ref, &tmp) < 0) {
        return -1;
    }
    else if (tmp == NULL) {
        return 1;
    }
    Py_DECREF(tmp);
    return 0;
}
```

In addition to not being ergonomic, the problem with this code is that the `Py_DECREF(tmp)` may introduce a side effect from a calling a destructor, at least in the free threading build where some other thread may concurrently drop the last reference. Our internal [`_PyWeakref_IS_DEAD`](https://github.com/python/cpython/blob/47cbf038850852cdcbe7a404ed7c64542340d58a/Include/internal/pycore_weakref.h#L85) implementation avoids this problem, but it's not possible to reimplement that code using our existing public APIs.

This can be a problem when you need to check if a weak reference is dead within a lock, such as when cleaning up dictionaries or lists of weak references -- you don't want to execute arbitrary code via a destructor while holding the lock.

I've run into this in two C API extensions this week that are not currently thread-safe with free threading:

* CFFI uses a [dictionary](https://github.com/python-cffi/cffi/blob/88f48d22484586d48079fc8780241dfdfa3379c8/src/c/_cffi_backend.c#L461-L468) that maps a string keys to unowned references. I'm working on update it to use `PyWeakReference`, but the "is dead" clean-up checks are more difficult due to the above issues.
* Pandas [cleans up](https://github.com/pandas-dev/pandas/blob/45aa7a55a5a1ef38c5e242488d2419ae84dd874b/pandas/_libs/internals.pyx#L912-L915) a list of weak references. (The code is not currently thread-safe, and probably needs a lock.)

### Vote

* [x] @encukou 
* [x] @erlend-aasland 
* [x] @mdboom 
* [x] @serhiy-storchaka 
* [x] @vstinner 
* [x] @zooba

**Comment by vstinner** [comment]
Your rationale makes sense so adding `int PyWeakref_IsDead(PyObject *ref)` LGTM.

I would just add an error case: raise an exception (TypeError) and return -1 if the argument is not a weak reference object.

**Comment by encukou** [comment]
An alternative is allowing `int PyWeakref_GetRef(ref, NULL)`.
IMO, we should generally default to allowing NULL for `PyObject **` output arguments, so that we can skip refcounting when the user doesn't need that result. It's very common that functions like this have other interesting effects, and it seems suboptimal to keep adding a separate “check” function some releases after the “get” function.
(Note that the *output argument* case is very different from accepting NULL for a `PyObject *` argument -- *that* is something to avoid, since it can easily come from a failed API call.)

Unfortunately, allowing the `NULL` now would mean that code tested on 3.14 will fail on 3.13. Even with that, I'd personally still slightly prefer `PyWeakref_GetRef(ref, NULL)`.
(If we go that way, in 3.13.1+ it should *fail with exception* if it gets a NULL.)

**Comment by colesbury** [comment]
I've updated the issue to specify a `-1` return value if the argument is not a weak reference object.

**Comment by serhiy-storchaka** [comment]
On one hand, `PyWeakref_IsDead` may be significantly more efficient. On other hand, how often do you need to know that the reference _was_ alive without getting its value? Note that the result can become obsolete right after obtaining it in a GIL-less build.

**Comment by colesbury** [comment]
@serhiy-storchaka - you need it any time you want to implement a collection of weakrefs (things like `WeakValueDictionary`) and things *like* that are pretty common. As I wrote above, I ran into this twice in a single week separately in pandas and cffi. You can find a number of other examples if you search GitHub.

It's not just a matter of efficiency. As I wrote in the issue:

> In addition to not being ergonomic, the problem with this code is that the Py_DECREF(tmp) may introduce a side effect from a calling a destructor, at least in the free threading build where some other thread may concurrently drop the last reference. Our internal [_PyWeakref_IS_DEAD](https://github.com/python/cpython/blob/47cbf038850852cdcbe7a404ed7c64542340d58a/Include/internal/pycore_weakref.h#L85) implementation avoids this problem, but it's not possible to reimplement that code using our existing public APIs.
>
> This can be a problem when you need to check if a weak reference is dead within a lock, such as when cleaning up dictionaries or lists of weak references -- you don't want to execute arbitrary code via a destructor while holding the lock.

**Comment by vstinner** [comment]
I added a vote in the first message: please vote :-)

**Comment by vstinner** [comment]
> Can we guarantee that it does not fail if the argument is a weakref?

**Comment by zooba** [comment]
In general, I agree with Petr that a NULL output argument and meaningful return value is the better pattern, but I dislike the transition plan we'd get if we did that now.

So I approve of this _as an exception_, not as a precedent. Let's try to avoid having separate APIs for "has/is" and "get" in the future if possible.

**Comment by vstinner** [comment]
@colesbury: Congrats, your API has been approved :-)

**Comment by vstinner** [comment]
Function implemented in https://github.com/python/cpython/issues/128008.
