### ISSUE TITLE
Add PyObject_GenericHash() function

### ISSUE THREAD

**Issue by serhiy-storchaka** [capi-workgroup/decisions#5]
Issue: https://github.com/python/cpython/issues/113024
PR: https://github.com/python/cpython/pull/113025

`Py_hash_t PyObject_GenericHash(PyObject *obj)`

It is the implementation of the default Python object hashing function `object.__hash__()`. In CPython it is identical to `Py_HashPointer()`, but has the signature compatible with `tp_hash`. It can only be used for Python objects, not arbitrary pointers, and it is more portable. It can be used in implementations that have no equivalence between object identity and object address.

`PyObject_GenericHash()` should be used for calculating the hash of Python object. `Py_HashPointer()` should be used for pointers not managed by Python object manger (i.e. static data, malloced data or pointers to C functions like `wrapperobject.descr`).

- [x] @gvanrossum 
- [x] @encukou (prefers rename)
- [x] @vstinner (+1)
- [x] @zooba (prefers Petr's rename)
- [x] @iritkatriel

**Comment by encukou** [comment]
+1 on the idea. I agree with the direction this is taking us, but I feel that this direction should be noted explicitly:
This is similar to API like `Py_Is` or *`PyRef_Dup`, which are equivalent to `==`/`Py_IncRef` on CPython, but signal that the author wants “HPy-like" semantics on implementations where they're available. IOW, this is acknowledging that HPy is a good idea :)

---

For this function specifically, I'd prefer calling it `PyObject_HashIdentity`. It should be used only for objects that are compared by identity, which doesn't sound too generic. (Other `Generic` API is, very roughly, functions added automatically to a subclass of a built-in type.)

**Comment by vstinner** [comment]
+1 to add the function. Using `PyObject_GenericHash(obj)` instead of `Py_HashDouble(obj)` should help to make code compatible with PyPy, and other Python implementations where id() doesn't directly return an object address, but something more complicated.

**Comment by hodgestar** [comment]
+1 on the function too. It looks like a great idea.

Regarding the name, why not just `PyObject_Hash`?

**Comment by fangerer** [comment]
> For this function specifically, I'd prefer calling it `PyObject_HashIdentity`.

👍

**Comment by encukou** [comment]
> Regarding the name, why not just PyObject_Hash?

That's a different function -- the equivalent of `hash(obj)`. It [already exists](https://docs.python.org/3/c-api/object.html#c.PyObject_Hash).

**Comment by hodgestar** [comment]
> > Regarding the name, why not just PyObject_Hash?
> 
> That's a different function -- the equivalent of `hash(obj)`. It [already exists](https://docs.python.org/3/c-api/object.html#c.PyObject_Hash).

Doh! Thanks for explaining. Now that I understand a bit better, having a function that returns a `Py_hash_t` equivalent of the identity sounds very useful for C extensions and HPy. It'll give people a simple alternative to using the `PyObject` pointer value as a hash.

**Comment by vstinner** [comment]
> And most importantly without replacing all assignments = and comparisons == with API calls.

I added Py_Is(x, y) function. Are you referring to that?

**Comment by vstinner** [comment]
Ping @iritkatriel and @gvanrossum: what's your opinion on this API?

**Comment by gvanrossum** [comment]
Looks like we're all in favor now.

**Comment by vstinner** [comment]
@serhiy-storchaka: Congrats, your API is approved, you can go ahead ;-)
